apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gdn-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: goldennotes-app
  template:
    metadata:
      labels:
        app: goldennotes-app
    spec:
        containers:
          - name: api-gdn-container
            image: gcr.io/goldennotes-app/api-gdn-container
          ports:
            - containerPort: 8080